[phases.setup]
nixPkgs = ["python311", "pip"]
nixLibs = ["zlib"]

[phases.install]
cmds = ["python3.11 -m pip install --upgrade pip", "python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "python3.11 -m uvicorn demo_main:app --host 0.0.0.0 --port $PORT"
